Repository osudroid/osu-droid, pull requests merged in 2022-06, with the labels that each got.

#192 Burst effect disabled when hidden mod is enabled.
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/S

#194 Revamped notification music player.
  res/drawable-hdpi/notify_clear.png
  res/drawable-hdpi/notify_left.png
  res/drawable-hdpi/notify_next.png
  res/drawable-hdpi/notify_pause.png
  res/drawable-hdpi/notify_play.png
  res/drawable-hdpi/notify_stop.png
  res/drawable-ldpi/notify_clear.png
  res/drawable-ldpi/notify_left.png
  res/drawable-ldpi/notify_next.png
  res/drawable-ldpi/notify_pause.png
  res/drawable-ldpi/notify_play.png
  res/drawable-ldpi/notify_stop.png
  res/drawable-mdpi/notify_clear.png
  res/drawable-mdpi/notify_left.png
  res/drawable-mdpi/notify_next.png
  res/drawable-mdpi/notify_pause.png
  res/drawable-mdpi/notify_play.png
  res/drawable-mdpi/notify_stop.png
  res/drawable-xhdpi/notify_clear.png
  res/drawable-xhdpi/notify_left.png
  res/drawable-xhdpi/notify_next.png
  res/drawable-xhdpi/notify_pause.png
  res/drawable-xhdpi/notify_play.png
  res/drawable-xhdpi/notify_stop.png
  res/drawable-xxhdpi/notify_clear.png
  res/drawable-xxhdpi/notify_left.png
  res/drawable-xxhdpi/notify_next.png
  res/drawable-xxhdpi/notify_pause.png
  res/drawable-xxhdpi/notify_play.png
  res/drawable-xxhdpi/notify_stop.png
  res/drawable-xxxhdpi/notify_clear.png
  res/drawable-xxxhdpi/notify_left.png
  res/drawable-xxxhdpi/notify_next.png
  res/drawable-xxxhdpi/notify_pause.png
  res/drawable-xxxhdpi/notify_play.png
  res/drawable-xxxhdpi/notify_stop.png
  res/drawable/v_close.xml
  res/drawable/v_next.xml
  res/drawable/v_pause.xml
  res/drawable/v_play.xml
  res/drawable/v_prev.xml
  res/layout/notify_small_layout.xml
  src/ru/nsu/ccfit/zuev/audio/serviceAudio/NotifyPlayer.java
  src/ru/nsu/ccfit/zuev/audio/serviceAudio/SaveServiceObject.java
  src/ru/nsu/ccfit/zuev/audio/serviceAudio/SongService.java
  src/ru/nsu/ccfit/zuev/osu/GlobalManager.java
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
Labels: size/XL

#195 Fix crash when 'Safe beatmap background' is enabled and the background is null.
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
Labels: size/XS

#197 Some refactoring and cleaning
  AndroidManifest.xml
  changelog.md
  default.properties
  keywords.txt
  lint.xml
  obfuscatedclasses.txt
  project.properties
  res/values-v11/theme.xml
  res/values-v14/theme.xml
  res/values-v9/styles.xml
  res/values/styles.xml
  res/values/theme.xml
  src/com/dgsrz/bancho/ui/LayeredGameActivity.java
  src/com/dgsrz/bancho/ui/SliderTestActivity.java
  src/com/dgsrz/bancho/ui/TouchEventTestActivity.java
  src/com/dgsrz/bancho/ui/VideoBackgroundTestActivity.java
  src/com/dgsrz/tpdifficulty/TimingPoint.java
  src/com/dgsrz/tpdifficulty/hitobject/HitCircle.java
  src/com/dgsrz/tpdifficulty/hitobject/HitObject.java
  src/com/dgsrz/tpdifficulty/hitobject/HitObjectType.java
  src/com/dgsrz/tpdifficulty/hitobject/Slider.java
  src/com/dgsrz/tpdifficulty/hitobject/SliderType.java
  src/com/dgsrz/tpdifficulty/hitobject/Spinner.java
  src/com/dgsrz/tpdifficulty/tp/AiModtpDifficulty.java
  src/com/dgsrz/tpdifficulty/tp/DifficultyType.java
  src/com/dgsrz/tpdifficulty/tp/tpHitObject.java
  src/ru/nsu/ccfit/zuev/osu/OSUParser.java
  src/ru/nsu/ccfit/zuev/osu/helper/DifficultyReCalculator.java
  todo.md
  todolist
Labels: size/XL
