Repository osudroid/osu-droid, pull requests merged in 2022-01, with the labels that each got.

#157 New Replay structure (Using floating points too)
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameObject.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/ModernSpinner.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
  src/ru/nsu/ccfit/zuev/osu/game/Spinner.java
  src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ResultType.java
  src/ru/nsu/ccfit/zuev/osu/scoring/TouchType.java
Labels: size/L

#170 Implement AR checking for Auto cursor
  src/ru/nsu/ccfit/zuev/osu/game/cursor/main/AutoCursor.java
Labels: size/XS

#171 Change Updater to be simpler
  src/ru/nsu/ccfit/zuev/osu/Updater.java
  src/ru/nsu/ccfit/zuev/osu/model/vo/GithubReleaseVO.java
  src/ru/nsu/ccfit/zuev/osu/model/vo/UpdateVO.java
  src/ru/nsu/ccfit/zuev/osu/model/vo/VersionCodeVO.java
Labels: size/L

#172 Minor changes
  assets/gfx/pause-save-replay.png
  res/layout/fragment_settings.xml
  res/values/strings.xml
  src/ru/nsu/ccfit/zuev/osu/Updater.java
  src/ru/nsu/ccfit/zuev/osu/menu/PauseMenu.java
Labels: size/M

#173 Fix crashes on devices running below Android 11
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/helper/FileUtils.java
Labels: size/M

#174 Fix AR checking for Auto cursor
  src/ru/nsu/ccfit/zuev/osu/game/cursor/main/AutoCursor.java
Labels: size/S
