Repository osudroid/osu-droid, pull requests merged in 2023-09, with the labels that each got.

#278 Optimize conversion methods in MultiplayerConverter.kt
  src/com/reco1l/legacy/data/MultiplayerConverter.kt
Labels: size/L

#277 Migrate some time properties to double
  src/ru/nsu/ccfit/zuev/audio/effect/Metronome.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameHelper.java
  src/ru/nsu/ccfit/zuev/osu/game/GameObjectListener.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
  src/ru/nsu/ccfit/zuev/osu/game/TimingPoint.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
Labels: size/L

#281 Fix crash when unknown input event is received
  AndEngine/src/org/anddev/andengine/extension/input/touch/controller/MultiTouchController.java
Labels: size/XS

#282 Rework leaderboard loading logic in SongMenu
  src/ru/nsu/ccfit/zuev/osu/ResourceManager.java
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
Labels: size/XL

#283 Some multiplayer fixes
  src/com/reco1l/legacy/ui/entity/BeatmapButton.kt
  src/com/reco1l/legacy/ui/multiplayer/RoomScene.kt
Labels: size/S

#284 Support personal best score in global leaderboard
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
Labels: size/S

#285 Rework in-game leaderboard
  src/com/reco1l/api/ibancho/data/Room.kt
  src/com/reco1l/api/ibancho/data/RoomTeam.kt
  src/com/reco1l/legacy/ui/entity/InGameLeaderboard.kt
  src/com/reco1l/legacy/ui/multiplayer/Multiplayer.kt
  src/ru/nsu/ccfit/zuev/osu/game/DuringGameScoreBoard.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/helper/StringTable.java
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoardItem.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
Labels: size/XL

#287 1.7.1 Fixes from here to there
  res/layout/fragment_in_game_option.xml
  src/com/edlplan/ui/fragment/InGameSettingMenu.java
  src/com/reco1l/api/ibancho/data/Room.kt
  src/com/reco1l/legacy/data/MultiplayerConverter.kt
  src/com/reco1l/legacy/ui/entity/InGameLeaderboard.kt
  src/com/reco1l/legacy/ui/multiplayer/LobbyRoomList.kt
  src/com/reco1l/legacy/ui/multiplayer/RoomMods.kt
  src/com/reco1l/legacy/ui/multiplayer/RoomPlayerList.kt
  src/com/reco1l/legacy/ui/multiplayer/RoomScene.kt
  src/ru/nsu/ccfit/zuev/osu/game/cursor/flashlight/FlashLightEntity.java
  src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
Labels: size/L

#289 Fix layering for storyboard with video
  res/xml/options.xml
  src/com/edlplan/framework/support/osb/StoryboardSprite.java
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/L

#288 Even more fixes for multiplayer mostly
  res/layout/fragment_in_game_option.xml
  src/com/edlplan/ui/fragment/InGameSettingMenu.java
  src/com/reco1l/legacy/ui/entity/InGameLeaderboard.kt
  src/com/reco1l/legacy/ui/entity/ScrollableList.kt
  src/com/reco1l/legacy/ui/multiplayer/LobbyRoomList.kt
  src/com/reco1l/legacy/ui/multiplayer/RoomPlayerList.kt
  src/com/reco1l/legacy/ui/multiplayer/RoomScene.kt
  src/com/reco1l/legacy/ui/multiplayer/StatisticSelector.kt
  src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
Labels: size/L
