Repository osudroid/osu-droid, pull requests merged in 2023-05, with the labels that each got.

#232 Improve game effects/visuals
  res/values/options.xml
  res/xml/options.xml
  src/com/edlplan/osu/support/slider/SliderBody2D.java
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/game/CircleNumber.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
Labels: size/XL

#233 Add chimu.moe support trough WebView
  assets/chimu.png
  build.gradle
  res/layout/fragment_chimu.xml
  res/layout/fragment_downloading.xml
  res/values/strings.xml
  src/com/reco1l/framework/lang/execution/Async.java
  src/com/reco1l/framework/net/Downloader.java
  src/com/reco1l/framework/net/IDownloaderObserver.java
  src/com/reco1l/framework/net/QueryContent.java
  src/com/reco1l/framework/net/Requester.java
  src/com/reco1l/framework/net/ResponseException.java
  src/com/reco1l/framework/net/SizeMeasure.java
  src/com/reco1l/framework/util/Algorithm.java
  src/com/reco1l/framework/util/FileUtil.java
  src/com/reco1l/framework/util/Logging.java
  src/com/reco1l/legacy/ui/ChimuWebView.java
  src/com/reco1l/legacy/ui/DownloadingFragment.java
  src/ru/nsu/ccfit/zuev/osu/LibraryManager.java
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
Labels: size/XXL

#234 Some fixes around animations and entity attaching
  src/ru/nsu/ccfit/zuev/osu/game/CircleNumber.java
  src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
  src/ru/nsu/ccfit/zuev/osu/helper/ModifierListener.java
Labels: size/L

#235 Fix bug when circles shows with initial alpha 1
  src/ru/nsu/ccfit/zuev/osu/game/CircleNumber.java
  src/ru/nsu/ccfit/zuev/osu/game/GameObject.java
  src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
Labels: size/M

#236 Improve intro animations
  res/layout/fragment_build_type_notice.xml
  res/values/styles.xml
  src/com/edlplan/ui/fragment/BuildTypeNoticeFragment.kt
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/menu/SplashScene.java
Labels: size/L

#237 Fix slider follow circle getting smaller if held for some time
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
Labels: size/S

#238 Refactor scoreboard and fix asynchronous scoreboard loading
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
Labels: size/XL

#239 Multiple fixes
  src/ru/nsu/ccfit/zuev/audio/serviceAudio/BassAudioFunc.java
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
  src/ru/nsu/ccfit/zuev/osu/menu/SplashScene.java
Labels: size/L

#240 Remove Handler usage & attach sprites on update thread when loading avatars
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
Labels: size/M

#242 Fix slider tick animation
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
Labels: size/S

#244 Fix a bug in LibraryManager where a loop may terminate prematurely
  src/ru/nsu/ccfit/zuev/osu/LibraryManager.java
Labels: size/S

#245 Fix slider follow circle tick animation to only play when there is no other animation playing
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
Labels: size/L
