Repository osudroid/osu-droid, pull requests merged in 2024-10, with the labels that each got.

#419 Optimize Engine's buffer updates and fix gameplay HUD discrepancy with osu!stable
  AndEngine/src/org/anddev/andengine/opengl/texture/atlas/TextureAtlas.java
  AndEngine/src/org/anddev/andengine/opengl/view/RenderSurfaceView.java
  assets/gfx/scorebar-marker.png
  src/com/edlplan/osu/support/slider/SliderBody.java
  src/com/reco1l/andengine/Anchor.kt
  src/com/reco1l/andengine/Axes.kt
  src/com/reco1l/andengine/BlendingFunction.kt
  src/com/reco1l/andengine/ExtendedEntity.kt
  src/com/reco1l/andengine/ExtendedScene.kt
  src/com/reco1l/andengine/container/Container.kt
  src/com/reco1l/andengine/container/LinearContainer.kt
  src/com/reco1l/andengine/modifier/IModifierChain.kt
  src/com/reco1l/andengine/modifier/UniversalModifier.kt
  src/com/reco1l/andengine/sprite/AnimatedSprite.kt
  src/com/reco1l/andengine/sprite/ExtendedSprite.kt
  src/com/reco1l/framework/ColorComponent.kt
  src/com/reco1l/framework/ColorTransformation.kt
  src/com/reco1l/framework/Interpolation.kt
  src/com/reco1l/osu/Colors.kt
  src/com/reco1l/osu/OsuColors.kt
  src/com/reco1l/osu/beatmaplisting/BeatmapListing.kt
  src/com/reco1l/osu/playfield/ComboCounter.kt
  src/com/reco1l/osu/playfield/FollowPointConnection.kt
  src/com/reco1l/osu/playfield/HealthDisplay.kt
  src/com/reco1l/osu/playfield/ScoreText.kt
  src/ru/nsu/ccfit/zuev/osu/ResourceManager.java
  src/ru/nsu/ccfit/zuev/osu/game/GameEffect.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplaySlider.java
  src/ru/nsu/ccfit/zuev/osu/game/ScoreBar.java
Labels: size/XXL

#422 Fix parallel modifiers potentially skipping the remaining time of an update thread when a nested modifier ends
  src/com/edlplan/ui/EasingHelper.java
  src/com/reco1l/andengine/ExtendedEntity.kt
  src/com/reco1l/andengine/ExtendedScene.kt
  src/com/reco1l/andengine/modifier/IModifierChain.kt
  src/com/reco1l/andengine/modifier/ModifierType.kt
  src/com/reco1l/andengine/modifier/UniversalModifier.kt
  src/com/reco1l/andengine/sprite/AnimatedSprite.kt
  src/com/reco1l/framework/ColorComponent.kt
  src/com/reco1l/framework/Easing.kt
  src/com/reco1l/framework/Pool.kt
  src/com/reco1l/osu/Modifiers.kt
  src/com/reco1l/osu/playfield/ComboCounter.kt
  src/com/reco1l/osu/playfield/FollowPointConnection.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplaySlider.java
Labels: size/XXL

#423 Optimize compound modifiers and fix potential deadlock due to floating point precision
  src/com/reco1l/andengine/modifier/UniversalModifier.kt
Labels: size/L

#424 Make gameplay HUD ignore playfield size setting and add option to change the score counter metric to display
  AndEngine/src/org/anddev/andengine/engine/camera/Camera.java
  res/values/options.xml
  res/xml/settings_gameplay.xml
  src/com/reco1l/andengine/ExtendedEntity.kt
  src/com/reco1l/osu/playfield/GameplayHUD.kt
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/L

#425 Implement osu!stable circular song progress
  AndEngine/src/org/anddev/andengine/entity/Entity.java
  AndEngine/src/org/anddev/andengine/entity/text/Text.java
  res/values/options.xml
  res/xml/settings_gameplay.xml
  src/com/edlplan/osu/support/slider/SliderBody.java
  src/com/reco1l/andengine/ExtendedEntity.kt
  src/com/reco1l/andengine/container/Container.kt
  src/com/reco1l/andengine/container/LinearContainer.kt
  src/com/reco1l/andengine/shape/Circle.kt
  src/com/reco1l/andengine/shape/Rectangle.kt
  src/com/reco1l/andengine/shape/TriangleMesh.kt
  src/com/reco1l/andengine/sprite/ExtendedSprite.kt
  src/com/reco1l/osu/hitobjects/FollowPoints.kt
  src/com/reco1l/osu/hitobjects/SliderTicks.kt
  src/com/reco1l/osu/playfield/CircularSongProgress.kt
  src/com/reco1l/osu/playfield/Counters.kt
  src/com/reco1l/osu/playfield/GameplayHUD.kt
  src/com/reco1l/osu/playfield/HealthBar.kt
  src/com/reco1l/osu/playfield/SpriteFont.kt
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplaySlider.java
  src/ru/nsu/ccfit/zuev/osu/game/LinearSongProgress.java
Labels: size/XL

#426 Refactor `ExtendedEntity` hierarchy, Implement `RoundedBox`, Implement `ScrollableContainer`, defer vertex buffer update calls and fix touch areas for `ExtendedEntity`s with custom origin
  src/com/reco1l/andengine/ExtendedEntity.kt
  src/com/reco1l/andengine/ExtendedScene.kt
  src/com/reco1l/andengine/container/ConstraintContainer.kt
  src/com/reco1l/andengine/container/Container.kt
  src/com/reco1l/andengine/container/LinearContainer.kt
  src/com/reco1l/andengine/container/ScrollableContainer.kt
  src/com/reco1l/andengine/shape/Box.kt
  src/com/reco1l/andengine/shape/Circle.kt
  src/com/reco1l/andengine/shape/Rectangle.kt
  src/com/reco1l/andengine/sprite/ExtendedSprite.kt
  src/com/reco1l/osu/playfield/CirclePiece.kt
  src/com/reco1l/osu/playfield/CircularSongProgress.kt
  src/com/reco1l/osu/playfield/GameplayHUD.kt
  src/com/reco1l/osu/playfield/HealthBar.kt
  src/com/reco1l/osu/playfield/SpriteFont.kt
  src/ru/nsu/ccfit/zuev/osu/game/CircleNumber.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/XXL

#427 Rework PP counter to show it along with score
  assets/gfx/score-d.png
  assets/gfx/score-p.png
  res/values/options.xml
  res/xml/settings_gameplay.xml
  src/com/reco1l/osu/playfield/Counters.kt
  src/com/reco1l/osu/playfield/GameplayHUD.kt
  src/com/reco1l/osu/playfield/SpriteFont.kt
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/L

#428 Corrections related to previous PRs
  src/com/reco1l/andengine/sprite/AnimatedSprite.kt
  src/com/reco1l/framework/Bitmaps.kt
  src/com/reco1l/osu/BuildUtils.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameEffect.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/L

#429 Updated and Added strings for locals
  build.gradle
  res/values/act_import_replay_res.xml
  res/values/options.xml
  res/values/score_menu_fragment.xml
  res/values/strings.xml
  res/values/strings_temporary_for_locals.xml
  res/xml/multiplayer_player_settings.xml
  res/xml/multiplayer_room_settings.xml
  res/xml/settings_advanced.xml
  res/xml/settings_audio.xml
  res/xml/settings_gameplay.xml
  res/xml/settings_general.xml
  res/xml/settings_graphics.xml
  res/xml/settings_input.xml
  res/xml/settings_library.xml
  src/com/edlplan/ui/ImportReplayActivity.java
  src/com/edlplan/ui/fragment/FavoriteManagerFragment.java
  src/com/edlplan/ui/fragment/FilterMenuFragment.kt
  src/com/edlplan/ui/fragment/ScoreMenuFragment.java
  src/com/reco1l/osu/AccessibilityDetector.kt
  src/com/reco1l/osu/UpdateManager.kt
  src/com/reco1l/osu/beatmaplisting/BeatmapDownloader.kt
  src/com/reco1l/osu/ui/SettingsFragment.kt
  src/com/reco1l/osu/ui/entity/MainMenu.kt
  src/com/rian/osu/beatmap/parser/BeatmapParser.kt
  src/ru/nsu/ccfit/zuev/osu/AppException.java
  src/ru/nsu/ccfit/zuev/osu/LibraryManager.java
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/RankedStatus.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/helper/FileUtils.java
  src/ru/nsu/ccfit/zuev/osu/menu/BeatmapSetItem.java
  src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
  src/ru/nsu/ccfit/zuev/osu/menu/PauseMenu.java
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlinePanel.java
  src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
Labels: size/XXL

#430 More corrections prior 1.8
  schemas/com.reco1l.osu.data.DroidDatabase/1.json
  src/com/reco1l/andengine/ExtendedEntity.kt
  src/com/reco1l/andengine/sprite/AnimatedSprite.kt
  src/com/reco1l/framework/Bitmaps.kt
  src/com/reco1l/framework/net/FileRequest.kt
  src/com/reco1l/framework/net/WebRequest.kt
  src/com/reco1l/osu/beatmaplisting/BeatmapDownloader.kt
  src/com/reco1l/osu/beatmaplisting/BeatmapListing.kt
  src/com/reco1l/osu/data/Beatmaps.kt
  src/com/reco1l/osu/data/Database.kt
  src/com/reco1l/osu/data/Scores.kt
  src/com/reco1l/osu/hitobjects/FollowPoints.kt
  src/com/reco1l/osu/playfield/Counters.kt
  src/com/reco1l/osu/ui/SettingsFragment.kt
  src/com/reco1l/osu/ui/entity/BeatmapButton.kt
  src/ru/nsu/ccfit/zuev/audio/BassSoundProvider.java
  src/ru/nsu/ccfit/zuev/osu/ResourceManager.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplaySlider.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
  src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
  src/ru/nsu/ccfit/zuev/skins/BeatmapSkinManager.java
Labels: size/L

#434 Synchronize StringTable, Change external osu!droid resources namespace, Set min SDK version to 24
  build.gradle
  src/com/edlplan/ui/ImportReplayActivity.java
  src/com/edlplan/ui/fragment/FavoriteManagerFragment.java
  src/com/edlplan/ui/fragment/FilterMenuFragment.kt
  src/com/edlplan/ui/fragment/ScoreMenuFragment.java
  src/com/reco1l/osu/AccessibilityDetector.kt
  src/com/reco1l/osu/UpdateManager.kt
  src/com/reco1l/osu/beatmaplisting/BeatmapDownloader.kt
  src/com/reco1l/osu/ui/SettingsFragment.kt
  src/com/reco1l/osu/ui/entity/MainMenu.kt
  src/com/rian/osu/beatmap/parser/BeatmapParser.kt
  src/ru/nsu/ccfit/zuev/osu/AppException.java
  src/ru/nsu/ccfit/zuev/osu/LibraryManager.java
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/RankedStatus.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/helper/FileUtils.java
  src/ru/nsu/ccfit/zuev/osu/helper/StringTable.java
  src/ru/nsu/ccfit/zuev/osu/menu/BeatmapSetItem.java
  src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
  src/ru/nsu/ccfit/zuev/osu/menu/PauseMenu.java
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlinePanel.java
  src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
Labels: size/L

#435 Slight optimize GameplayLeaderboard
  src/com/reco1l/osu/ui/entity/GameplayLeaderboard.kt
Labels: size/S

#436 Refactor, document and format `com.reco1l` package
  src/com/reco1l/BuildUtils.kt
  src/com/reco1l/andengine/Modifiers.kt
  src/com/reco1l/framework/Bitmaps.kt
  src/com/reco1l/framework/Interpolation.kt
  src/com/reco1l/ibancho/IPlayerEventListener.kt
  src/com/reco1l/ibancho/IRoomEventListener.kt
  src/com/reco1l/ibancho/LobbyAPI.kt
  src/com/reco1l/ibancho/RoomAPI.kt
  src/com/reco1l/ibancho/data/Parsing.kt
  src/com/reco1l/ibancho/data/PlayerStatus.kt
  src/com/reco1l/ibancho/data/Room.kt
  src/com/reco1l/ibancho/data/RoomBeatmap.kt
  src/com/reco1l/ibancho/data/RoomMods.kt
  src/com/reco1l/ibancho/data/RoomPlayer.kt
  src/com/reco1l/ibancho/data/RoomStatus.kt
  src/com/reco1l/ibancho/data/RoomTeam.kt
  src/com/reco1l/ibancho/data/TeamMode.kt
  src/com/reco1l/ibancho/data/WinCondition.kt
  src/com/reco1l/osu/AccessibilityDetector.kt
  src/com/reco1l/osu/Execution.kt
  src/com/reco1l/osu/ExecutionOverloads.kt
  src/com/reco1l/osu/beatmaplisting/BeatmapListing.kt
  src/com/reco1l/osu/multiplayer/LobbyCreateRoom.kt
  src/com/reco1l/osu/multiplayer/LobbyRoomList.kt
  src/com/reco1l/osu/multiplayer/LobbyScene.kt
  src/com/reco1l/osu/multiplayer/LobbySearch.kt
  src/com/reco1l/osu/multiplayer/Multiplayer.kt
  src/com/reco1l/osu/multiplayer/MultiplayerConversion.kt
  src/com/reco1l/osu/multiplayer/RoomChat.kt
  src/com/reco1l/osu/multiplayer/RoomPlayerList.kt
  src/com/reco1l/osu/multiplayer/RoomPlayerMenu.kt
  src/com/reco1l/osu/multiplayer/RoomScene.kt
  src/com/reco1l/osu/skinning/SkinConversion.kt
  src/com/reco1l/osu/skinning/SkinIniReader.kt
  src/com/reco1l/osu/ui/SettingsFragment.kt
  src/com/reco1l/osu/ui/entity/BeatmapButton.kt
  src/com/reco1l/osu/ui/entity/ComposedText.kt
  src/com/reco1l/osu/ui/entity/GameplayLeaderboard.kt
  src/com/reco1l/osu/ui/entity/MainMenu.kt
  src/com/reco1l/osu/ui/entity/ScrollableList.kt
  src/com/reco1l/osu/ui/entity/StatisticSelector.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameEffect.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplayHitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplayModernSpinner.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplaySlider.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplaySpinner.java
  src/ru/nsu/ccfit/zuev/osu/game/cursor/main/AutoCursor.java
  src/ru/nsu/ccfit/zuev/osu/helper/QualityAssetBitmapSource.java
  src/ru/nsu/ccfit/zuev/osu/helper/QualityFileBitmapSource.java
  src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoardItem.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
Labels: size/XXL
