Repository osudroid/osu-droid, pull requests merged in 2024-03, with the labels that each got.

#336 Fix storyboard
  src/com/edlplan/framework/support/osb/StoryboardSprite.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/L

#337 Normalize all asynchronous methods in one
  src/com/edlplan/osu/support/slider/SliderBody2D.java
  src/com/edlplan/ui/fragment/FilterMenuFragment.kt
  src/com/edlplan/ui/fragment/InGameSettingMenu.kt
  src/com/reco1l/framework/lang/Execution.kt
  src/com/reco1l/framework/lang/execution/Async.java
  src/com/reco1l/legacy/UpdateManager.kt
  src/com/reco1l/legacy/ui/multiplayer/LobbyCreateRoom.kt
  src/com/reco1l/legacy/ui/multiplayer/LobbyRoomList.kt
  src/com/reco1l/legacy/ui/multiplayer/LobbyScene.kt
  src/com/reco1l/legacy/ui/multiplayer/RoomChat.kt
  src/com/reco1l/legacy/ui/multiplayer/RoomOptions.kt
  src/com/reco1l/legacy/ui/multiplayer/RoomScene.kt
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/async/SyncTaskManager.java
  src/ru/nsu/ccfit/zuev/osu/game/FollowTrack.java
  src/ru/nsu/ccfit/zuev/osu/game/GameEffect.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/ModernSpinner.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
  src/ru/nsu/ccfit/zuev/osu/game/Spinner.java
  src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
  src/ru/nsu/ccfit/zuev/osu/menu/SettingsMenu.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
  src/ru/nsu/ccfit/zuev/osu/menu/SplashScene.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlineScoring.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
Labels: size/L

#341 Some GameScene class refactor and simplification.
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/mods/GameMod.java
Labels: size/L

#342 Fix crash when trying to show an alert outside UI thread.
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
Labels: size/M

#340 Combine score and replay uploads into one HTTP request
  src/ru/nsu/ccfit/zuev/osu/online/FormDataPostBuilder.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlineFileOperator.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlineManager.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlineScoring.java
  src/ru/nsu/ccfit/zuev/osu/online/PostBuilder.java
  src/ru/nsu/ccfit/zuev/osu/online/URLEncodedPostBuilder.java
Labels: size/L

#344 Replace score with pp in `OnlinePanel` and add pp to `SendingPanel`
  src/com/rian/osu/ui/SendingPanel.kt
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlineManager.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlinePanel.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlineScoring.java
  src/ru/nsu/ccfit/zuev/osu/online/SendingPanel.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoreLibrary.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
Labels: size/XL
