Repository osudroid/osu-droid, pull requests merged in 2024-04, with the labels that each got.

#343 Add beatmapset ranking status
  assets/selection-approved.png
  assets/selection-loved.png
  assets/selection-question.png
  assets/selection-ranked.png
  src/com/edlplan/ui/fragment/PropsMenuFragment.java
  src/com/rian/osu/difficulty/BeatmapDifficultyCalculator.kt
  src/com/rian/osu/utils/LRUCache.kt
  src/ru/nsu/ccfit/zuev/osu/RankedStatus.java
  src/ru/nsu/ccfit/zuev/osu/ResourceManager.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlineManager.java
Labels: size/L

#346 Remove Chimu integration and replace with a multiple beatmap mirror system
  LibBASS/src/main/jniLibs/arm64-v8a/libbass_ssl.so
  LibBASS/src/main/jniLibs/armeabi-v7a/libbass_ssl.so
  LibBASS/src/main/jniLibs/x86/libbass_ssl.so
  LibBASS/src/main/jniLibs/x86_64/libbass_ssl.so
  assets/beatmap_downloader.png
  assets/chimu.png
  res/drawable/arrow_back_24px.xml
  res/drawable/download_24px.xml
  res/drawable/pause_24px.xml
  res/drawable/play_arrow_24px.xml
  res/drawable/powered_by_osudirect.png
  res/drawable/search_24px.xml
  res/layout/beatmap_downloader_details.xml
  res/layout/beatmap_downloader_fragment.xml
  res/layout/beatmap_downloader_set_item.xml
  res/layout/fragment_chimu.xml
  res/values/dimensions.xml
  res/values/strings.xml
  res/values/styles.xml
  src/com/reco1l/api/chimu/CheesegullAPI.kt
  src/com/reco1l/framework/annotation/Algorithm.java
  src/com/reco1l/framework/annotation/JsonName.kt
  src/com/reco1l/framework/bass/URLBassStream.kt
  src/com/reco1l/framework/extensions/FileExt.kt
  src/com/reco1l/framework/net/JsonRequester.kt
  src/com/reco1l/legacy/UpdateManager.kt
  src/com/reco1l/legacy/ui/ChimuWebView.kt
  src/com/reco1l/legacy/ui/Colors.kt
  src/com/reco1l/legacy/ui/DownloadFragment.kt
  src/com/reco1l/legacy/ui/DownloadingFragment.kt
  src/com/reco1l/legacy/ui/MainMenu.kt
  src/com/reco1l/legacy/ui/beatmapdownloader/BeatmapDownloader.kt
  src/com/reco1l/legacy/ui/beatmapdownloader/BeatmapListing.kt
  src/com/reco1l/legacy/ui/beatmapdownloader/BeatmapMirror.kt
  src/com/reco1l/legacy/ui/beatmapdownloader/BeatmapModel.kt
  src/com/reco1l/legacy/ui/entity/BeatmapButton.kt
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/RankedStatus.java
Labels: size/XXL

#351 Fix touch events being recorded with update thread clock
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
Labels: size/S
