Repository osudroid/osu-droid, pull requests merged in 2024-08, with the labels that each got.

#376 Simplify mod display in ScoringScene
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
Labels: size/M

#383 Use always 'MultiTouchController' ignoring screen capabilities
  AndEngine/src/org/anddev/andengine/extension/input/touch/controller/MultiTouchController.java
  res/values/strings.xml
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
Labels: size/M

#374 Pool entity modifiers and remove unnecessary `Sprite` pooling
  AndEngine/src/org/anddev/andengine/entity/Entity.java
  AndEngine/src/org/anddev/andengine/util/modifier/IModifier.java
  src/com/edlplan/osu/support/slider/SliderBody2D.java
  src/com/reco1l/framework/Pool.kt
  src/com/reco1l/osu/graphics/Modifiers.kt
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/game/BreakAnimator.java
  src/ru/nsu/ccfit/zuev/osu/game/CircleNumber.java
  src/ru/nsu/ccfit/zuev/osu/game/FollowTrack.java
  src/ru/nsu/ccfit/zuev/osu/game/GameEffect.java
  src/ru/nsu/ccfit/zuev/osu/game/GameObjectPool.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/ModernSpinner.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
  src/ru/nsu/ccfit/zuev/osu/game/Spinner.java
  src/ru/nsu/ccfit/zuev/osu/game/SpritePool.java
  src/ru/nsu/ccfit/zuev/osu/helper/CentredSprite.java
  src/ru/nsu/ccfit/zuev/osu/helper/ModifierFactory.java
  src/ru/nsu/ccfit/zuev/osu/helper/UniversalModifier.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoreNumber.java
Labels: size/XXL

#387 Process hitobject combo information
  src/com/rian/osu/beatmap/BeatmapConverter.kt
  src/com/rian/osu/beatmap/BeatmapProcessor.kt
  src/com/rian/osu/beatmap/hitobject/HitCircle.kt
  src/com/rian/osu/beatmap/hitobject/HitObject.kt
  src/com/rian/osu/beatmap/hitobject/Slider.kt
  src/com/rian/osu/beatmap/hitobject/Spinner.kt
  src/com/rian/osu/beatmap/hitobject/sliderobject/SliderHitObject.kt
  src/com/rian/osu/beatmap/parser/BeatmapParser.kt
  src/com/rian/osu/beatmap/parser/sections/BeatmapHitObjectsParser.kt
Labels: size/L

#384 Unify control point processing
  src/com/edlplan/osu/support/timing/TimingPoint.java
  src/com/edlplan/osu/support/timing/TimingPoints.java
  src/com/edlplan/osu/support/timing/controlpoint/ControlPoint.java
  src/com/edlplan/osu/support/timing/controlpoint/ControlPoints.java
  src/com/edlplan/osu/support/timing/controlpoint/DifficultyControlPoint.java
  src/com/edlplan/osu/support/timing/controlpoint/EffectControlPoint.java
  src/com/edlplan/osu/support/timing/controlpoint/SampleControlPoint.java
  src/com/edlplan/osu/support/timing/controlpoint/TimingControlPoint.java
  src/com/rian/osu/beatmap/Beatmap.kt
  src/com/rian/osu/beatmap/parser/sections/BeatmapControlPointsParser.kt
  src/com/rian/osu/beatmap/timings/ControlPointManager.kt
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameHelper.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
  src/ru/nsu/ccfit/zuev/osu/game/TimingPoint.java
Labels: size/XL

#380 Replace beatmap library cache system with a database table using Room API
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/com/edlplan/ext/EdExtensionHelper.java
  src/com/edlplan/ui/fragment/InGameSettingMenu.kt
  src/com/edlplan/ui/fragment/PropsMenuFragment.kt
  src/com/reco1l/osu/Beatmaps.kt
  src/com/reco1l/osu/Database.kt
  src/com/reco1l/osu/beatmaplisting/BeatmapDownloader.kt
  src/com/reco1l/osu/multiplayer/LobbyCreateRoom.kt
  src/com/reco1l/osu/multiplayer/LobbyScene.kt
  src/com/reco1l/osu/multiplayer/RoomScene.kt
  src/com/reco1l/osu/ui/SettingsFragment.kt
  src/com/reco1l/osu/ui/entity/BeatmapButton.kt
  src/com/reco1l/osu/ui/entity/MainMenu.kt
  src/com/reco1l/osu/ui/entity/StatisticSelector.kt
  src/ru/nsu/ccfit/zuev/audio/serviceAudio/NotifyPlayer.java
  src/ru/nsu/ccfit/zuev/osu/BeatmapInfo.java
  src/ru/nsu/ccfit/zuev/osu/GlobalManager.java
  src/ru/nsu/ccfit/zuev/osu/LibraryManager.java
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/TrackInfo.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/helper/FileUtils.java
  src/ru/nsu/ccfit/zuev/osu/menu/BeatmapItem.java
  src/ru/nsu/ccfit/zuev/osu/menu/BeatmapSetItem.java
  src/ru/nsu/ccfit/zuev/osu/menu/IPropsMenu.java
  src/ru/nsu/ccfit/zuev/osu/menu/MenuItemBackground.java
  src/ru/nsu/ccfit/zuev/osu/menu/MenuItemListener.java
  src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenuPool.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlineManager.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlineScoring.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoreLibrary.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
Labels: size/XXL

#389 Rework old beatmap properties JSON to use a database table with Room API
  src/com/edlplan/ui/fragment/PropsMenuFragment.kt
  src/com/reco1l/osu/Database.kt
  src/com/reco1l/osu/data/BeatmapInfo.kt
  src/com/reco1l/osu/data/BeatmapOptions.kt
  src/com/reco1l/osu/data/BeatmapSetInfo.kt
  src/com/reco1l/osu/data/Database.kt
  src/com/reco1l/osu/ui/SettingsFragment.kt
  src/ru/nsu/ccfit/zuev/audio/serviceAudio/NotifyPlayer.java
  src/ru/nsu/ccfit/zuev/osu/BeatmapProperties.java
  src/ru/nsu/ccfit/zuev/osu/GlobalManager.java
  src/ru/nsu/ccfit/zuev/osu/LibraryManager.java
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/PropertiesLibrary.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/menu/BeatmapItem.java
  src/ru/nsu/ccfit/zuev/osu/menu/BeatmapSetItem.java
  src/ru/nsu/ccfit/zuev/osu/menu/MenuItemListener.java
  src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlineManager.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlineScoring.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
Labels: size/XL

#392 Redo beatmap code restructure.
  src/com/reco1l/osu/data/BeatmapSets.kt
  src/com/reco1l/osu/data/Beatmaps.kt
  src/ru/nsu/ccfit/zuev/osu/LibraryManager.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
Labels: size/L

#393 Unify time multiplier application
  src/ru/nsu/ccfit/zuev/osu/game/GameHelper.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/ModernSpinner.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
  src/ru/nsu/ccfit/zuev/osu/game/Spinner.java
Labels: size/L

#396 Fix modifiers setting a wrong value
  src/com/reco1l/osu/graphics/Modifiers.kt
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
Labels: size/S

#400 Remove unused `dgsrz` package & move `SecurityUtils` to main package
  src/com/dgsrz/bancho/ui/StoryBoardTestActivity.java
  src/com/reco1l/ibancho/RoomAPI.kt
  src/com/reco1l/osu/multiplayer/LobbyCreateRoom.kt
  src/com/reco1l/osu/multiplayer/LobbyScene.kt
  src/ru/nsu/ccfit/zuev/osu/ResourceManager.java
  src/ru/nsu/ccfit/zuev/osu/SecurityUtils.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/online/PostBuilder.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
  src/ru/nsu/ccfit/zuev/osu/storyboard/Command.java
  src/ru/nsu/ccfit/zuev/osu/storyboard/HitSound.java
  src/ru/nsu/ccfit/zuev/osu/storyboard/OsbParser.java
  src/ru/nsu/ccfit/zuev/osu/storyboard/OsuEvent.java
  src/ru/nsu/ccfit/zuev/osu/storyboard/OsuSprite.java
  src/ru/nsu/ccfit/zuev/osu/storyboard/TimingPoint.java
Labels: size/XXL

#399 Substitute `GameObjectData` with pre-calculated `HitObject` properties from beatmap parsing
  assets/sfx/drum-sliderslide.ogg
  assets/sfx/drum-sliderwhistle.ogg
  assets/sfx/normal-sliderslide.ogg
  assets/sfx/normal-sliderwhistle.ogg
  assets/sfx/soft-sliderslide.ogg
  assets/sfx/soft-sliderwhistle.ogg
  res/values/options.xml
  res/xml/settings_advanced.xml
  src/com/edlplan/osu/support/object/StdPath.java
  src/com/edlplan/osu/support/object/StdSliderPathMaker.java
  src/com/edlplan/osu/support/object/SupportSliderPath.java
  src/com/rian/osu/beatmap/Beatmap.kt
  src/com/rian/osu/beatmap/BeatmapConverter.kt
  src/com/rian/osu/beatmap/BeatmapProcessor.kt
  src/com/rian/osu/beatmap/hitobject/BankHitSampleInfo.kt
  src/com/rian/osu/beatmap/hitobject/FileHitSampleInfo.kt
  src/com/rian/osu/beatmap/hitobject/HitObject.kt
  src/com/rian/osu/beatmap/hitobject/HitObjectExt.kt
  src/com/rian/osu/beatmap/hitobject/HitSampleInfo.kt
  src/com/rian/osu/beatmap/hitobject/Slider.kt
  src/com/rian/osu/beatmap/hitobject/Spinner.kt
  src/com/rian/osu/beatmap/parser/BeatmapParser.kt
  src/com/rian/osu/beatmap/parser/sections/BeatmapHitObjectsParser.kt
  src/com/rian/osu/difficulty/DifficultyHitObject.kt
  src/com/rian/osu/difficulty/DroidDifficultyHitObject.kt
  src/com/rian/osu/difficulty/StandardDifficultyHitObject.kt
  src/com/rian/osu/difficulty/evaluators/DroidFlashlightEvaluator.kt
  src/com/rian/osu/difficulty/evaluators/DroidVisualEvaluator.kt
  src/com/rian/osu/difficulty/evaluators/StandardFlashlightEvaluator.kt
  src/com/rian/osu/math/Vector2.kt
  src/com/rian/osu/mods/ModEasy.kt
  src/com/rian/osu/mods/ModHardRock.kt
  src/com/rian/osu/mods/ModReallyEasy.kt
  src/com/rian/osu/replay/SliderCheeseChecker.kt
  src/com/rian/osu/replay/ThreeFingerChecker.kt
  src/com/rian/osu/utils/CircleSizeCalculator.kt
  src/ru/nsu/ccfit/zuev/audio/effect/Metronome.java
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/Constants.java
  src/ru/nsu/ccfit/zuev/osu/ResourceManager.java
  src/ru/nsu/ccfit/zuev/osu/Utils.java
  src/ru/nsu/ccfit/zuev/osu/game/FollowTrack.java
  src/ru/nsu/ccfit/zuev/osu/game/GameHelper.java
  src/ru/nsu/ccfit/zuev/osu/game/GameObject.java
  src/ru/nsu/ccfit/zuev/osu/game/GameObjectData.java
  src/ru/nsu/ccfit/zuev/osu/game/GameObjectListener.java
  src/ru/nsu/ccfit/zuev/osu/game/GameObjectPool.java
  src/ru/nsu/ccfit/zuev/osu/game/GameObjectSize.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/ModernSpinner.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
  src/ru/nsu/ccfit/zuev/osu/game/Spinner.java
  src/ru/nsu/ccfit/zuev/osu/polygon/Spline.java
  src/ru/nsu/ccfit/zuev/osu/scoring/Statistic.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
Labels: size/XXL

#402 Remove unused classes
  src/com/edlplan/andengine/Triangle3DBuilder.java
  src/com/edlplan/andengine/Triangle3DPack.java
  src/com/edlplan/andengine/Triangle3DRenderer.java
  src/com/edlplan/andengine/TrianglePack.java
  src/com/edlplan/andengine/TriangleTexture3DPack.java
  src/com/edlplan/andengine/TriangleTexture3DRenderer.java
  src/com/edlplan/andengine/texture/AbstractTexture.java
  src/com/edlplan/andengine/texture/GLTexture.java
  src/com/edlplan/framework/support/timing/AbstractClock.java
  src/com/edlplan/framework/support/timing/FrameClock.java
  src/com/edlplan/framework/support/timing/IHasIntervalSchedule.java
  src/com/edlplan/framework/support/timing/ILooper.java
  src/com/edlplan/framework/support/timing/IRunnableHandler.java
  src/com/edlplan/framework/support/timing/Loopable.java
  src/com/edlplan/framework/support/timing/MTimer.java
  src/com/edlplan/framework/support/timing/RunnableHandler.java
  src/com/edlplan/osu/support/SampleSet.java
  src/com/edlplan/osu/support/slider/Draw3DLinePath.java
  src/com/edlplan/osu/support/slider/SliderBody3D.java
  src/com/edlplan/ui/InvalidateView.java
  src/com/edlplan/ui/TriangleDrawable.java
  src/com/edlplan/ui/TriangleEffectView.java
  src/com/edlplan/ui/design/IColor.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/RGBAColor.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/SongProgressBar.java
  src/ru/nsu/ccfit/zuev/osu/polygon/Polygon.java
  src/ru/nsu/ccfit/zuev/osu/polygon/PolygonVertexBuffer.java
Labels: size/XXL

#398 Implement input block area to prevent accidental touch
  res/drawable/add_24px.xml
  res/drawable/block_area_background.xml
  res/drawable/check_24px.xml
  res/drawable/drag_indicator_24px.xml
  res/drawable/expand_content_24px.xml
  res/drawable/open_with_24px.xml
  res/drawable/restart_alt_24px.xml
  res/layout/block_area_editor_fragment.xml
  res/layout/block_area_editor_item.xml
  res/layout/block_area_layer_fragment.xml
  res/layout/block_area_layer_item.xml
  res/values/strings.xml
  res/xml/settings_input.xml
  src/com/edlplan/ui/ActivityOverlay.kt
  src/com/edlplan/ui/fragment/BaseFragment.kt
  src/com/reco1l/osu/data/BlockArea.kt
  src/com/reco1l/osu/data/Database.kt
  src/com/reco1l/osu/ui/BlockAreaFragment.kt
  src/com/reco1l/osu/ui/SettingsFragment.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/XL

#394 Replace absolute path references in database columns with filenames
  src/com/edlplan/replay/OsuDroidReplayPack.java
  src/com/edlplan/ui/ImportReplayActivity.java
  src/com/edlplan/ui/fragment/PropsMenuFragment.kt
  src/com/edlplan/ui/fragment/ScoreMenuFragment.java
  src/com/reco1l/osu/data/BeatmapOptions.kt
  src/com/reco1l/osu/data/BeatmapSets.kt
  src/com/reco1l/osu/data/Beatmaps.kt
  src/com/reco1l/osu/data/Database.kt
  src/com/reco1l/osu/data/Scores.kt
  src/com/reco1l/osu/multiplayer/RoomScene.kt
  src/com/reco1l/osu/ui/SettingsFragment.kt
  src/ru/nsu/ccfit/zuev/audio/serviceAudio/NotifyPlayer.java
  src/ru/nsu/ccfit/zuev/osu/BeatmapProperties.java
  src/ru/nsu/ccfit/zuev/osu/LibraryManager.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/helper/sql/DBOpenHelper.java
  src/ru/nsu/ccfit/zuev/osu/helper/sql/DatabaseContext.java
  src/ru/nsu/ccfit/zuev/osu/menu/BeatmapItem.java
  src/ru/nsu/ccfit/zuev/osu/menu/BeatmapSetItem.java
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlineManager.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
Labels: size/XL

#397 Rework old collections system with a Room database table
  src/com/edlplan/favorite/FavoriteLibrary.java
  src/com/edlplan/ui/fragment/FavoriteManagerFragment.java
  src/com/reco1l/osu/data/BeatmapCollections.kt
  src/com/reco1l/osu/data/Database.kt
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/menu/BeatmapSetItem.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
Labels: size/L

#404 Impose maximum hit range restriction to circles and sliders
  src/ru/nsu/ccfit/zuev/osu/game/GameObject.java
  src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
Labels: size/M

#405 Improve old database system migration
  src/com/edlplan/ui/fragment/PropsMenuFragment.kt
  src/com/reco1l/osu/data/BeatmapCollections.kt
  src/com/reco1l/osu/data/BeatmapOptions.kt
  src/com/reco1l/osu/data/Database.kt
  src/com/reco1l/osu/data/Scores.kt
Labels: size/M

#391 Implement asynchronous difficulty calculation for beatmaps
  res/layout/loading_badge_fragment.xml
  res/layout/settings_fragment.xml
  schemas/com.reco1l.osu.data.DroidDatabase/1.json
  schemas/com.reco1l.osu.data.DroidDatabase/2.json
  src/com/reco1l/osu/DifficultyCalculation.kt
  src/com/reco1l/osu/data/Beatmaps.kt
  src/com/reco1l/osu/multiplayer/RoomScene.kt
  src/com/reco1l/osu/ui/entity/BeatmapButton.kt
  src/com/rian/osu/ui/DifficultyAlgorithmSwitcher.kt
  src/ru/nsu/ccfit/zuev/osu/LibraryManager.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/menu/BeatmapItem.java
  src/ru/nsu/ccfit/zuev/osu/menu/BeatmapSetItem.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
Labels: size/XXL
