Repository osudroid/osu-droid, pull requests merged in 2024-09, with the labels that each got.

#406 Fix bugs related to latest pull requests
  res/drawable/rounded_half_bottom.xml
  res/drawable/rounded_half_left.xml
  res/drawable/rounded_half_right.xml
  res/drawable/rounded_half_top.xml
  res/drawable/rounded_rect.xml
  res/layout/mod_customization_fragment.xml
  res/layout/settings_preference_input.xml
  res/layout/settings_preference_input_bottom.xml
  src/com/edlplan/ui/fragment/InGameSettingMenu.kt
  src/com/edlplan/ui/fragment/PropsMenuFragment.kt
  src/com/reco1l/osu/data/BeatmapOptions.kt
  src/com/reco1l/osu/data/BeatmapSets.kt
  src/com/reco1l/osu/data/Beatmaps.kt
  src/com/reco1l/osu/data/BlockArea.kt
  src/com/reco1l/osu/data/Database.kt
  src/com/reco1l/osu/data/Scores.kt
  src/com/reco1l/osu/graphics/Modifiers.kt
  src/com/reco1l/osu/ui/BlockAreaFragment.kt
  src/com/reco1l/osu/ui/SettingsFragment.kt
  src/ru/nsu/ccfit/zuev/osu/BeatmapProperties.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/Spinner.java
  src/ru/nsu/ccfit/zuev/osu/menu/BeatmapSetItem.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
Labels: size/L

#407 Add pp for global beatmap leaderboard in song selection
  res/values/options.xml
  res/values/strings.xml
  res/xml/settings_general.xml
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlineManager.java
  src/ru/nsu/ccfit/zuev/osu/online/OnlineScoring.java
  src/ru/nsu/ccfit/zuev/osu/scoring/BeatmapLeaderboardScoringMode.java
Labels: size/L

#409 Group nested hit object sprites in a container, Introduce extended `Entity` and correct gameplay animations
  AndEngine/src/org/anddev/andengine/collision/RectangularShapeCollisionChecker.java
  AndEngine/src/org/anddev/andengine/entity/Entity.java
  AndEngine/src/org/anddev/andengine/util/modifier/ModifierList.java
  res/values/strings.xml
  res/xml/settings_graphics.xml
  src/com/edlplan/andengine/SpriteCache.java
  src/com/edlplan/andengine/TrianglePack.java
  src/com/edlplan/osu/support/slider/SliderBody.java
  src/com/edlplan/osu/support/slider/SliderBody2D.java
  src/com/reco1l/osu/graphics/AnimatedSprite.kt
  src/com/reco1l/osu/graphics/ExtendedEntity.kt
  src/com/reco1l/osu/graphics/ExtendedSprite.kt
  src/com/reco1l/osu/graphics/Modifiers.kt
  src/com/reco1l/osu/graphics/TriangleMesh.kt
  src/com/reco1l/osu/multiplayer/LobbyScene.kt
  src/com/reco1l/osu/multiplayer/RoomScene.kt
  src/com/reco1l/osu/playfield/CirclePiece.kt
  src/com/reco1l/osu/playfield/ScoreText.kt
  src/com/reco1l/osu/playfield/SliderTickContainer.kt
  src/com/reco1l/osu/ui/entity/MainMenu.kt
  src/com/rian/osu/ui/DifficultyAlgorithmSwitcher.kt
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/game/BreakAnimator.java
  src/ru/nsu/ccfit/zuev/osu/game/CircleNumber.java
  src/ru/nsu/ccfit/zuev/osu/game/Countdown.java
  src/ru/nsu/ccfit/zuev/osu/game/FollowTrack.java
  src/ru/nsu/ccfit/zuev/osu/game/GameEffect.java
  src/ru/nsu/ccfit/zuev/osu/game/GameObjectPool.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScoreText.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScoreTextShadow.java
  src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/ModernSpinner.java
  src/ru/nsu/ccfit/zuev/osu/game/ScoreBar.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
  src/ru/nsu/ccfit/zuev/osu/game/Spinner.java
  src/ru/nsu/ccfit/zuev/osu/helper/AnimSprite.java
  src/ru/nsu/ccfit/zuev/osu/helper/CentredSprite.java
  src/ru/nsu/ccfit/zuev/osu/helper/ModifierListener.java
  src/ru/nsu/ccfit/zuev/osu/menu/LoadingScreen.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
  src/ru/nsu/ccfit/zuev/skins/SkinLayout.java
Labels: size/XXL

#410 Fix regressions from past pull request
  src/com/reco1l/osu/DifficultyCalculation.kt
  src/com/reco1l/osu/data/Scores.kt
  src/com/reco1l/osu/graphics/AnimatedSprite.kt
  src/com/reco1l/osu/graphics/Modifiers.kt
  src/com/reco1l/osu/multiplayer/RoomScene.kt
  src/ru/nsu/ccfit/zuev/osu/game/FollowTrack.java
  src/ru/nsu/ccfit/zuev/osu/game/GameObject.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
  src/ru/nsu/ccfit/zuev/osu/game/Spinner.java
  src/ru/nsu/ccfit/zuev/osu/game/cursor/main/AutoCursor.java
  src/ru/nsu/ccfit/zuev/osu/menu/LoadingScreen.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
Labels: size/L

#411 Introduce ExtendedScene and apply clock rate changes at scene level
  src/com/reco1l/osu/graphics/ExtendedScene.kt
  src/com/reco1l/osu/playfield/ScoreText.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/ModernSpinner.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
  src/ru/nsu/ccfit/zuev/osu/game/Spinner.java
  src/ru/nsu/ccfit/zuev/osu/game/cursor/trail/CursorTrail.java
Labels: size/L

#412 Match osu!stable follow point rendering, make `sliderfollowcircle` animatable and fix frames count for animatable textures
  src/com/reco1l/framework/Pool.kt
  src/com/reco1l/osu/graphics/AnimatedSprite.kt
  src/com/reco1l/osu/graphics/ExtendedSprite.kt
  src/com/reco1l/osu/graphics/Modifiers.kt
  src/com/reco1l/osu/multiplayer/LobbyScene.kt
  src/com/reco1l/osu/multiplayer/RoomScene.kt
  src/com/reco1l/osu/playfield/FollowPointConnection.kt
  src/com/reco1l/osu/skinning/SkinConversion.kt
  src/ru/nsu/ccfit/zuev/osu/ResourceManager.java
  src/ru/nsu/ccfit/zuev/osu/game/FollowTrack.java
  src/ru/nsu/ccfit/zuev/osu/game/GameEffect.java
  src/ru/nsu/ccfit/zuev/osu/game/GameObjectPool.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/ScoreBar.java
  src/ru/nsu/ccfit/zuev/osu/game/Slider.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
  src/ru/nsu/ccfit/zuev/skins/OsuSkin.java
  src/ru/nsu/ccfit/zuev/skins/SkinJsonReader.java
  src/ru/nsu/ccfit/zuev/skins/SkinManager.java
Labels: size/XL

#414 Block area finetune
  res/layout/block_area_editor_item.xml
  src/com/reco1l/osu/ui/BlockAreaFragment.kt
Labels: size/S

#416 Add support for coroutine cancellation in beatmap parsing and difficulty calculation
  src/com/rian/osu/beatmap/Beatmap.kt
  src/com/rian/osu/beatmap/BeatmapConverter.kt
  src/com/rian/osu/beatmap/BeatmapProcessor.kt
  src/com/rian/osu/beatmap/parser/BeatmapParser.kt
  src/com/rian/osu/beatmap/parser/sections/BeatmapColorParser.kt
  src/com/rian/osu/beatmap/parser/sections/BeatmapControlPointsParser.kt
  src/com/rian/osu/beatmap/parser/sections/BeatmapDifficultyParser.kt
  src/com/rian/osu/beatmap/parser/sections/BeatmapEventsParser.kt
  src/com/rian/osu/beatmap/parser/sections/BeatmapGeneralParser.kt
  src/com/rian/osu/beatmap/parser/sections/BeatmapHitObjectsParser.kt
  src/com/rian/osu/beatmap/parser/sections/BeatmapKeyValueSectionParser.kt
  src/com/rian/osu/beatmap/parser/sections/BeatmapMetadataParser.kt
  src/com/rian/osu/beatmap/parser/sections/BeatmapSectionParser.kt
  src/com/rian/osu/difficulty/BeatmapDifficultyCalculator.kt
  src/com/rian/osu/difficulty/calculator/DifficultyCalculator.kt
  src/com/rian/osu/difficulty/calculator/DroidDifficultyCalculator.kt
  src/com/rian/osu/difficulty/calculator/StandardDifficultyCalculator.kt
Labels: size/L

#417 Use coroutine in background difficulty calculation
  src/com/reco1l/osu/DifficultyCalculation.kt
  src/com/reco1l/osu/data/Beatmaps.kt
Labels: size/L
