Repository osudroid/osu-droid, pull requests merged in 2025-05, with the labels that each got.

#532 Pre-implementation of customizable theme system across all entities of UI v2
  assets/check.png
  src/com/osudroid/debug/CollapsiblePanel.kt
  src/com/osudroid/ui/v2/GameLoaderScene.kt
  src/com/osudroid/ui/v2/SkinnableSprite.kt
  src/com/osudroid/ui/v2/game/FollowPoints.kt
  src/com/osudroid/ui/v2/hud/elements/HUDAccuracyCounter.kt
  src/com/osudroid/ui/v2/hud/elements/HUDComboCounter.kt
  src/com/osudroid/ui/v2/hud/elements/HUDHealthBar.kt
  src/com/osudroid/ui/v2/hud/elements/HUDPPCounter.kt
  src/com/osudroid/ui/v2/hud/elements/HUDScoreCounter.kt
  src/com/osudroid/ui/v2/hud/elements/HUDSongProgress.kt
  src/com/osudroid/ui/v2/modmenu/ModCustomizationMenu.kt
  src/com/osudroid/ui/v2/modmenu/ModIcon.kt
  src/com/osudroid/ui/v2/modmenu/ModMenu.kt
  src/com/osudroid/ui/v2/modmenu/ModMenuSection.kt
  src/com/osudroid/ui/v2/modmenu/ModMenuToggle.kt
  src/com/reco1l/andengine/EntityCollisionChecker.kt
  src/com/reco1l/andengine/ExtendedEngine.kt
  src/com/reco1l/andengine/ExtendedEntity.kt
  src/com/reco1l/andengine/Initializers.kt
  src/com/reco1l/andengine/InvalidationFlag.kt
  src/com/reco1l/andengine/container/Container.kt
  src/com/reco1l/andengine/container/LinearContainer.kt
  src/com/reco1l/andengine/container/ScrollableContainer.kt
  src/com/reco1l/andengine/shape/Box.kt
  src/com/reco1l/andengine/shape/TriangleMesh.kt
  src/com/reco1l/andengine/sprite/ExtendedSprite.kt
  src/com/reco1l/andengine/text/ExtendedText.kt
  src/com/reco1l/andengine/ui/Badge.kt
  src/com/reco1l/andengine/ui/Button.kt
  src/com/reco1l/andengine/ui/Card.kt
  src/com/reco1l/andengine/ui/Checkbox.kt
  src/com/reco1l/andengine/ui/CircularProgressBar.kt
  src/com/reco1l/andengine/ui/IFocusable.kt
  src/com/reco1l/andengine/ui/ISkinnable.kt
  src/com/reco1l/andengine/ui/Modal.kt
  src/com/reco1l/andengine/ui/Slider.kt
  src/com/reco1l/andengine/ui/Theme.kt
  src/com/reco1l/andengine/ui/form/FormCheckbox.kt
  src/com/reco1l/andengine/ui/form/FormControl.kt
  src/com/reco1l/andengine/ui/form/FormSlider.kt
  src/com/reco1l/framework/ColorComponent.kt
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/ResourceManager.java
Labels: size/XXL

#531 Partially match stacking behavior with osu!stable
  res/values/strings_temporary_for_locals.xml
  src/com/edlplan/replay/OsuDroidReplayPack.java
  src/com/osudroid/ui/v2/modmenu/ModMenu.kt
  src/com/rian/osu/beatmap/Beatmap.kt
  src/com/rian/osu/beatmap/BeatmapProcessor.kt
  src/com/rian/osu/beatmap/hitobject/HitObject.kt
  src/com/rian/osu/beatmap/hitobject/Slider.kt
  src/com/rian/osu/difficulty/calculator/DroidDifficultyCalculator.kt
  src/com/rian/osu/mods/IModApplicableToBeatmap.kt
  src/com/rian/osu/mods/Mod.kt
  src/com/rian/osu/mods/ModHidden.kt
  src/com/rian/osu/mods/ModReplayV6.kt
  src/com/rian/osu/mods/ModTimeRamp.kt
  src/com/rian/osu/mods/ModType.kt
  src/com/rian/osu/utils/ModHashMap.kt
  src/com/rian/osu/utils/ModUtils.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
  tests/test/kotlin/com/rian/osu/difficulty/calculator/DroidDifficultyCalculatorTest.kt
  tests/test/kotlin/com/rian/osu/difficulty/calculator/StandardDifficultyCalculatorTest.kt
  tests/test/kotlin/com/rian/osu/mods/ModReplayV6Test.kt
  tests/test/kotlin/com/rian/osu/utils/ModUtilsTest.kt
Labels: size/L

#533 Fix object scale being device height dependent
  src/com/osudroid/ui/v2/game/FollowPoints.kt
  src/com/osudroid/ui/v2/game/SliderTicks.kt
  src/com/rian/osu/beatmap/Beatmap.kt
  src/com/rian/osu/beatmap/hitobject/HitObject.kt
  src/com/rian/osu/beatmap/hitobject/Slider.kt
  src/com/rian/osu/beatmap/hitobject/Spinner.kt
  src/com/rian/osu/mods/IModApplicableToDifficulty.kt
  src/com/rian/osu/mods/IModApplicableToDifficultyWithMods.kt
  src/com/rian/osu/mods/IModApplicableToHitObject.kt
  src/com/rian/osu/mods/IModApplicableToHitObjectWithMods.kt
  src/com/rian/osu/mods/IModFacilitatesAdjustment.kt
  src/com/rian/osu/mods/ModDifficultyAdjust.kt
  src/com/rian/osu/mods/ModEasy.kt
  src/com/rian/osu/mods/ModHardRock.kt
  src/com/rian/osu/mods/ModMirror.kt
  src/com/rian/osu/mods/ModPrecise.kt
  src/com/rian/osu/mods/ModReallyEasy.kt
  src/com/rian/osu/mods/ModReplayV6.kt
  src/com/rian/osu/mods/ModSmallCircle.kt
  src/com/rian/osu/utils/CircleSizeCalculator.kt
  src/com/rian/osu/utils/ModUtils.kt
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplayHitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplaySlider.java
  src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
  tests/test/kotlin/com/rian/osu/beatmap/DroidPlayableBeatmapTest.kt
  tests/test/kotlin/com/rian/osu/difficulty/calculator/DroidDifficultyCalculatorTest.kt
  tests/test/kotlin/com/rian/osu/mods/ModEasyTest.kt
  tests/test/kotlin/com/rian/osu/mods/ModHardRockTest.kt
  tests/test/kotlin/com/rian/osu/mods/ModPreciseTest.kt
  tests/test/kotlin/com/rian/osu/mods/ModReallyEasyTest.kt
  tests/test/kotlin/com/rian/osu/mods/ModReplayV6Test.kt
  tests/test/kotlin/com/rian/osu/mods/ModSmallCircleTest.kt
  tests/test/kotlin/com/rian/osu/utils/CircleSizeCalculatorTest.kt
Labels: size/XL

#518 Submit serialized `Mod`s in solo score submission
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
Labels: size/XS

#535 Add Random mod
  assets/gfx/selection-mod-random.png
  src/com/rian/osu/beatmap/hitobject/Slider.kt
  src/com/rian/osu/beatmap/hitobject/SliderPath.kt
  src/com/rian/osu/difficulty/calculator/DifficultyCalculator.kt
  src/com/rian/osu/math/Random.kt
  src/com/rian/osu/math/Vector4.kt
  src/com/rian/osu/mods/ModRandom.kt
  src/com/rian/osu/utils/HitObjectGenerationUtils.kt
  src/com/rian/osu/utils/ModHashMap.kt
  src/com/rian/osu/utils/ModUtils.kt
  tests/test/kotlin/com/rian/osu/math/RandomTest.kt
  tests/test/kotlin/com/rian/osu/mods/ModRandomTest.kt
  tests/test/kotlin/com/rian/osu/utils/HitObjectGenerationUtilsTest.kt
Labels: size/XXL

#540 Add Freeze Frame mod
  assets/gfx/selection-mod-freezeframe.png
  src/com/rian/osu/mods/ModFreezeFrame.kt
  src/com/rian/osu/utils/ModHashMap.kt
  src/com/rian/osu/utils/ModUtils.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameHelper.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplayHitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplaySlider.java
Labels: size/L

#536 Implement `TextInput` control & Implement mod presets user interface
  src/com/osudroid/data/ModPresets.kt
  src/com/osudroid/ui/v2/GameLoaderScene.kt
  src/com/osudroid/ui/v2/ModsIndicator.kt
  src/com/osudroid/ui/v2/modmenu/ModCustomizationMenu.kt
  src/com/osudroid/ui/v2/modmenu/ModMenu.kt
  src/com/osudroid/ui/v2/modmenu/ModMenuPresetsSection.kt
  src/com/osudroid/ui/v2/modmenu/ModMenuSection.kt
  src/com/osudroid/ui/v2/modmenu/ModPresetsForm.kt
  src/com/reco1l/andengine/Cameras.kt
  src/com/reco1l/andengine/ExtendedEngine.kt
  src/com/reco1l/andengine/ui/Button.kt
  src/com/reco1l/andengine/ui/Modal.kt
  src/com/reco1l/andengine/ui/TextInput.kt
  src/com/reco1l/andengine/ui/form/FormControl.kt
  src/com/reco1l/andengine/ui/form/FormInput.kt
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
Labels: size/XL

#541 Add support for text input based `ModSetting`
  src/com/osudroid/ui/v2/modmenu/ModCustomizationMenu.kt
  src/com/osudroid/ui/v2/modmenu/ModSettingCheckbox.kt
  src/com/osudroid/ui/v2/modmenu/ModSettingComponent.kt
  src/com/osudroid/ui/v2/modmenu/ModSettingSlider.kt
  src/com/osudroid/ui/v2/modmenu/ModSettingTextInput.kt
  src/com/reco1l/andengine/ui/TextInput.kt
  src/com/reco1l/andengine/ui/form/FormInput.kt
  src/com/rian/osu/mods/ModDifficultyAdjust.kt
  src/com/rian/osu/mods/ModRandom.kt
  src/com/rian/osu/mods/ModSetting.kt
Labels: size/XL
