Repository osudroid/osu-droid, pull requests merged in 2025-02, with the labels that each got.

#480 fix download speed unit
  src/com/reco1l/osu/beatmaplisting/BeatmapDownloader.kt
Labels: size/XS

#481 Fix fragments not being displayed properly
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
Labels: size/S

#482 Fix GL_STACK_UNDERFLOW on glPopMatrix
  AndEngine/src/org/anddev/andengine/entity/scene/CameraScene.java
Labels: size/XS

#484 Fix wrong blending function being applied to object if no text is present on screen
  src/com/reco1l/andengine/BlendInfo.kt
  src/com/reco1l/andengine/ExtendedEntity.kt
  src/com/reco1l/osu/playfield/HealthBar.kt
Labels: size/M

#488 Minor optimization during gameplay
  src/com/rian/osu/replay/SliderCheeseChecker.kt
  src/com/rian/osu/replay/ThreeFingerChecker.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/cursor/main/CursorSprite.java
  src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
Labels: size/L
