Repository osudroid/osu-droid, pull requests merged in 2025-04, with the labels that each got.

#515 Add support for serializing `Mod`s into a JSON
  src/com/reco1l/ibancho/data/RoomMods.kt
  src/com/reco1l/osu/data/Scores.kt
  src/com/reco1l/osu/multiplayer/MultiplayerConversion.kt
  src/com/rian/osu/mods/ILegacyMod.kt
  src/com/rian/osu/mods/IMigratableMod.kt
  src/com/rian/osu/mods/IModUserSelectable.kt
  src/com/rian/osu/mods/LegacyModConverter.kt
  src/com/rian/osu/mods/Mod.kt
  src/com/rian/osu/mods/ModAuto.kt
  src/com/rian/osu/mods/ModAutopilot.kt
  src/com/rian/osu/mods/ModCustomSpeed.kt
  src/com/rian/osu/mods/ModDifficultyAdjust.kt
  src/com/rian/osu/mods/ModDoubleTime.kt
  src/com/rian/osu/mods/ModEasy.kt
  src/com/rian/osu/mods/ModFlashlight.kt
  src/com/rian/osu/mods/ModHalfTime.kt
  src/com/rian/osu/mods/ModHardRock.kt
  src/com/rian/osu/mods/ModHidden.kt
  src/com/rian/osu/mods/ModNightCore.kt
  src/com/rian/osu/mods/ModNoFail.kt
  src/com/rian/osu/mods/ModPerfect.kt
  src/com/rian/osu/mods/ModPrecise.kt
  src/com/rian/osu/mods/ModRateAdjust.kt
  src/com/rian/osu/mods/ModReallyEasy.kt
  src/com/rian/osu/mods/ModRelax.kt
  src/com/rian/osu/mods/ModScoreV2.kt
  src/com/rian/osu/mods/ModSetting.kt
  src/com/rian/osu/mods/ModSmallCircle.kt
  src/com/rian/osu/mods/ModSuddenDeath.kt
  src/com/rian/osu/mods/ModTimeRamp.kt
  src/com/rian/osu/mods/ModTraceable.kt
  src/com/rian/osu/utils/ModHashMap.kt
  src/com/rian/osu/utils/ModUtils.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/mods/IModSwitcher.java
  src/ru/nsu/ccfit/zuev/osu/game/mods/ModButton.java
  src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
  src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
  src/ru/nsu/ccfit/zuev/osu/scoring/ScoringScene.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
Labels: size/XXL

#522 Implement UI components based on `ExtendedEntity`
  src/com/reco1l/andengine/shape/BezelOutline.kt
  src/com/reco1l/andengine/ui/Badge.kt
  src/com/reco1l/andengine/ui/Button.kt
  src/com/reco1l/andengine/ui/Checkbox.kt
  src/com/reco1l/andengine/ui/Control.kt
  src/com/reco1l/andengine/ui/Modal.kt
  src/com/reco1l/andengine/ui/Slider.kt
  src/com/reco1l/andengine/ui/Theme.kt
  src/com/reco1l/andengine/ui/form/FormCheckbox.kt
  src/com/reco1l/andengine/ui/form/FormControl.kt
  src/com/reco1l/andengine/ui/form/FormSlider.kt
Labels: size/XXL

#516 Store stringified `Mod` JSON in replays
  src/com/rian/osu/utils/ModHashMap.kt
  src/ru/nsu/ccfit/zuev/osu/scoring/Replay.java
Labels: size/M

#524 Add unit and integration tests to core beatmap parsing components
  .github/workflows/android.yml
  .run/Run Unit Tests.run.xml
  build.gradle
  tests/test/kotlin/TestResourceManager.kt
  tests/test/kotlin/com/rian/osu/beatmap/BeatmapTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/DroidHitWindowTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/DroidPlayableBeatmapTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/EmptyHitWindowTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/HitWindowTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/PlayableBeatmapTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/PreciseDroidHitWindowTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/StandardHitWindowTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/StandardPlayableBeatmapTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/hitobject/HitCircleTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/hitobject/HitObjectTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/hitobject/SliderPathTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/hitobject/SpinnerTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/parser/BeatmapParserTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/sections/BeatmapHitObjectsTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/timings/ControlPointManagerTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/timings/DifficultyControlPointTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/timings/EffectControlPointTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/timings/SampleControlPointTest.kt
  tests/test/kotlin/com/rian/osu/beatmap/timings/TimingControlPointTest.kt
  tests/test/kotlin/com/rian/osu/difficulty/DroidDifficultyHitObjectTest.kt
  tests/test/kotlin/com/rian/osu/difficulty/StandardDifficultyHitObjectTest.kt
  tests/test/kotlin/com/rian/osu/difficulty/calculator/DroidDifficultyCalculatorTest.kt
  tests/test/kotlin/com/rian/osu/difficulty/calculator/StandardDifficultyCalculatorTest.kt
  tests/test/kotlin/com/rian/osu/math/ErrorFunctionTest.kt
  tests/test/kotlin/com/rian/osu/math/InterpolationTest.kt
  tests/test/kotlin/com/rian/osu/math/PolynomialTest.kt
  tests/test/kotlin/com/rian/osu/math/PrecisionTest.kt
  tests/test/kotlin/com/rian/osu/math/Vector2Test.kt
  tests/test/kotlin/com/rian/osu/mods/LegacyModConverterTest.kt
  tests/test/kotlin/com/rian/osu/utils/CachedTest.kt
  tests/test/kotlin/com/rian/osu/utils/CircleSizeCalculatorTest.kt
  tests/test/kotlin/com/rian/osu/utils/LRUCacheTest.kt
  tests/test/kotlin/com/rian/osu/utils/ModHashMapTest.kt
  tests/test/kotlin/com/rian/osu/utils/ModUtilsTest.kt
  tests/test/kotlin/com/rian/osu/utils/PathApproximationTest.kt
  tests/test/resources/beatmaps/Kenji Ninuma - DISCOPRINCE (peppy) [Normal].osu
  tests/test/resources/beatmaps/YOASOBI - Love Letter (ohm002) [Please accept my overflowing emotions.].osu
  tests/test/resources/beatmaps/nan-control-points.osu
Labels: size/XXL

#519 Migrate mods in score table to new mods format
  build.gradle
  schemas/com.reco1l.osu.data.DroidDatabase/2.json
  src/com/reco1l/osu/data/Database.kt
  src/com/reco1l/osu/data/Migrations.kt
  src/com/reco1l/osu/data/Scores.kt
  tests/test/kotlin/com/reco1l/osu/data/MigrationTest.kt
Labels: size/XL

#520 Add legacy mods format compatibility to exported replay
  src/com/edlplan/replay/OsuDroidReplayPack.java
  src/com/reco1l/osu/data/Scores.kt
Labels: size/S

#517 Communicate mods with `JSONArray` in multiplayer
  src/com/reco1l/ibancho/LobbyAPI.kt
  src/com/reco1l/ibancho/RoomAPI.kt
  src/com/reco1l/ibancho/data/Parsing.kt
  src/com/reco1l/ibancho/data/RoomMods.kt
  src/com/reco1l/osu/multiplayer/RoomScene.kt
  src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
Labels: size/M

#526 Refactor engine's debugging tools and introduce `EntityInspector`
  src/com/reco1l/BuildConfiguration.kt
  src/com/reco1l/andengine/Anchor.kt
  src/com/reco1l/andengine/ExtendedEngine.kt
  src/com/reco1l/andengine/ExtendedEntity.kt
  src/com/reco1l/andengine/buffered/BufferInvalidationFlag.kt
  src/com/reco1l/andengine/buffered/BufferedEntity.kt
  src/com/reco1l/andengine/buffered/CompoundBuffer.kt
  src/com/reco1l/andengine/buffered/CompoundBufferedEntity.kt
  src/com/reco1l/andengine/buffered/VertexBuffer.kt
  src/com/reco1l/andengine/container/ScrollableContainer.kt
  src/com/reco1l/andengine/shape/BezelOutline.kt
  src/com/reco1l/andengine/shape/Box.kt
  src/com/reco1l/andengine/shape/Circle.kt
  src/com/reco1l/andengine/shape/Line.kt
  src/com/reco1l/andengine/shape/OutlineBox.kt
  src/com/reco1l/andengine/shape/PaintStyle.kt
  src/com/reco1l/andengine/shape/RoundedBox.kt
  src/com/reco1l/andengine/shape/Triangle.kt
  src/com/reco1l/andengine/sprite/ExtendedSprite.kt
  src/com/reco1l/andengine/text/ExtendedText.kt
  src/com/reco1l/andengine/text/TextureFont.kt
  src/com/reco1l/andengine/ui/Badge.kt
  src/com/reco1l/andengine/ui/Button.kt
  src/com/reco1l/andengine/ui/Checkbox.kt
  src/com/reco1l/andengine/ui/Modal.kt
  src/com/reco1l/andengine/ui/Slider.kt
  src/com/reco1l/andengine/ui/form/FormControl.kt
  src/com/reco1l/andengine/ui/form/FormSlider.kt
  src/com/reco1l/debug/CollapsiblePanel.kt
  src/com/reco1l/debug/EntityDescriptor.kt
  src/com/reco1l/debug/EntityInspector.kt
  src/com/reco1l/debug/MockMultiplayer.kt
  src/com/reco1l/framework/Bitmaps.kt
  src/com/reco1l/ibancho/LobbyAPI.kt
  src/com/reco1l/ibancho/RoomAPI.kt
  src/com/reco1l/osu/beatmaplisting/BeatmapListing.kt
  src/com/reco1l/osu/hud/editor/HUDElementOverlay.kt
  src/com/reco1l/osu/hud/editor/HUDElementPreview.kt
  src/com/reco1l/osu/hud/editor/HUDElementSelector.kt
  src/com/reco1l/osu/hud/elements/HUDHitErrorMeter.kt
  src/com/reco1l/osu/multiplayer/RoomScene.kt
  src/com/reco1l/osu/ui/entity/MainMenu.kt
  src/com/reco1l/osu/ui/modmenu/ModCustomizationMenu.kt
  src/com/reco1l/osu/ui/modmenu/ModIcon.kt
  src/com/reco1l/osu/ui/modmenu/ModMenu.kt
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/MainScene.java
  src/ru/nsu/ccfit/zuev/osu/helper/QualityAssetBitmapSource.java
  src/ru/nsu/ccfit/zuev/osu/helper/QualityFileBitmapSource.java
Labels: size/XXL

#529 Rework loading scene prior to game start
  assets/minus.png
  assets/plus.png
  assets/warning.png
  schemas/com.osudroid.data.DroidDatabase/2.json
  src/com/osudroid/data/Beatmaps.kt
  src/com/osudroid/data/Migrations.kt
  src/com/osudroid/debug/CollapsiblePanel.kt
  src/com/osudroid/debug/EntityInspector.kt
  src/com/osudroid/multiplayer/RoomScene.kt
  src/com/osudroid/ui/v2/GameLoaderScene.kt
  src/com/osudroid/ui/v2/ModsIndicator.kt
  src/com/osudroid/ui/v2/hud/editor/HUDElementOverlay.kt
  src/com/osudroid/ui/v2/hud/editor/HUDElementPreview.kt
  src/com/osudroid/ui/v2/hud/editor/HUDElementSelector.kt
  src/com/osudroid/ui/v2/hud/elements/HUDSongProgress.kt
  src/com/osudroid/ui/v2/modmenu/ModCustomizationMenu.kt
  src/com/osudroid/ui/v2/modmenu/ModIcon.kt
  src/com/osudroid/ui/v2/modmenu/ModMenu.kt
  src/com/osudroid/ui/v2/modmenu/ModMenuSection.kt
  src/com/osudroid/ui/v2/modmenu/ModMenuToggle.kt
  src/com/reco1l/andengine/ExtendedEntity.kt
  src/com/reco1l/andengine/Initializers.kt
  src/com/reco1l/andengine/buffered/BufferedEntity.kt
  src/com/reco1l/andengine/buffered/VertexBuffer.kt
  src/com/reco1l/andengine/container/Container.kt
  src/com/reco1l/andengine/container/LinearContainer.kt
  src/com/reco1l/andengine/shape/Box.kt
  src/com/reco1l/andengine/shape/Circle.kt
  src/com/reco1l/andengine/sprite/ExtendedSprite.kt
  src/com/reco1l/andengine/text/ExtendedText.kt
  src/com/reco1l/andengine/text/TextureFont.kt
  src/com/reco1l/andengine/ui/Badge.kt
  src/com/reco1l/andengine/ui/Button.kt
  src/com/reco1l/andengine/ui/Card.kt
  src/com/reco1l/andengine/ui/CircularProgressBar.kt
  src/com/reco1l/andengine/ui/Modal.kt
  src/com/reco1l/andengine/ui/Slider.kt
  src/com/reco1l/andengine/ui/form/FormCheckbox.kt
  src/com/reco1l/andengine/ui/form/FormControl.kt
  src/com/reco1l/andengine/ui/form/FormSlider.kt
  src/com/rian/osu/beatmap/parser/sections/BeatmapGeneralParser.kt
  src/com/rian/osu/beatmap/sections/BeatmapGeneral.kt
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/XXL
