Repository osudroid/osu-droid, pull requests merged in 2025-03, with the labels that each got.

#485 Implement HUD layout editor
  assets/delete.png
  assets/one-one.png
  res/values/strings_temporary_for_locals.xml
  res/xml/settings_gameplay.xml
  src/com/edlplan/ui/fragment/ModSettingsMenu.kt
  src/com/reco1l/andengine/Anchor.kt
  src/com/reco1l/andengine/Entities.kt
  src/com/reco1l/andengine/ExtendedEntity.kt
  src/com/reco1l/andengine/container/ConstraintContainer.kt
  src/com/reco1l/andengine/container/ScrollableContainer.kt
  src/com/reco1l/andengine/modifier/IModifierChain.kt
  src/com/reco1l/andengine/modifier/ModifierType.kt
  src/com/reco1l/andengine/shape/Line.kt
  src/com/reco1l/andengine/shape/OutlineBox.kt
  src/com/reco1l/andengine/text/ExtendedText.kt
  src/com/reco1l/andengine/text/TextureFont.kt
  src/com/reco1l/framework/math/Vec2.kt
  src/com/reco1l/osu/hud/GameplayHUD.kt
  src/com/reco1l/osu/hud/HUDElement.kt
  src/com/reco1l/osu/hud/HUDSkinData.kt
  src/com/reco1l/osu/hud/IGameplayEvents.kt
  src/com/reco1l/osu/hud/editor/HUDElementOverlay.kt
  src/com/reco1l/osu/hud/editor/HUDElementPreview.kt
  src/com/reco1l/osu/hud/editor/HUDElementSelector.kt
  src/com/reco1l/osu/hud/elements/HUDAccuracyCounter.kt
  src/com/reco1l/osu/hud/elements/HUDAverageOffsetCounter.kt
  src/com/reco1l/osu/hud/elements/HUDComboCounter.kt
  src/com/reco1l/osu/hud/elements/HUDHealthBar.kt
  src/com/reco1l/osu/hud/elements/HUDHitErrorMeter.kt
  src/com/reco1l/osu/hud/elements/HUDLinearSongProgress.kt
  src/com/reco1l/osu/hud/elements/HUDPPCounter.kt
  src/com/reco1l/osu/hud/elements/HUDPieSongProgress.kt
  src/com/reco1l/osu/hud/elements/HUDScoreCounter.kt
  src/com/reco1l/osu/hud/elements/HUDUnstableRateCounter.kt
  src/com/reco1l/osu/playfield/Counters.kt
  src/com/reco1l/osu/playfield/GameplayHUD.kt
  src/com/reco1l/osu/ui/Dialog.kt
  src/com/reco1l/osu/ui/SettingsFragment.kt
  src/com/reco1l/osu/ui/entity/GameplayLeaderboard.kt
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/HitErrorMeter.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
  src/ru/nsu/ccfit/zuev/skins/OsuSkin.java
  src/ru/nsu/ccfit/zuev/skins/SkinJsonReader.java
Labels: size/XXL

#492 Some corrections to HUD editor
  assets/one-one.png
  assets/restore.png
  src/com/reco1l/osu/hud/GameplayHUD.kt
  src/com/reco1l/osu/hud/HUDElement.kt
  src/com/reco1l/osu/hud/HUDSkinData.kt
  src/com/reco1l/osu/hud/editor/HUDElementOverlay.kt
  src/com/reco1l/osu/hud/elements/HUDStatisticsCounters.kt
  src/com/reco1l/osu/multiplayer/Multiplayer.kt
  src/com/reco1l/osu/ui/Dialog.kt
  src/com/reco1l/osu/ui/entity/GameplayLeaderboard.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/L

#494 Fix banner swapping breaking after clicking on the banner
  src/com/reco1l/osu/Banners.kt
Labels: size/S

#496 Improve hit error meter readability and minor optimization
  src/com/reco1l/osu/hud/elements/HUDHitErrorMeter.kt
Labels: size/M

#495 Replace navigation bar with virtual back button
  assets/back-arrow.png
  res/values/styles.xml
  res/xml/settings_graphics.xml
  res/xml/settings_input.xml
  src/com/reco1l/andengine/shape/Circle.kt
  src/com/reco1l/osu/hud/HUDElement.kt
  src/com/reco1l/osu/hud/HUDSkinData.kt
  src/com/reco1l/osu/hud/elements/HUDBackButton.kt
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/MainActivity.java
Labels: size/L

#497 Optimize hit error meter to reduce memory usage
  src/com/reco1l/osu/hud/GameplayHUD.kt
  src/com/reco1l/osu/hud/elements/HUDHitErrorMeter.kt
Labels: size/M

#500 Add notes per second counter
  src/com/reco1l/osu/hud/GameplayHUD.kt
  src/com/reco1l/osu/hud/HUDElement.kt
  src/com/reco1l/osu/hud/IGameplayEvents.kt
  src/com/reco1l/osu/hud/editor/HUDElementSelector.kt
  src/com/reco1l/osu/hud/elements/HUDNotesPerSecondCounter.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/M

#501 Add taps per second counter
  src/com/reco1l/osu/hud/GameplayHUD.kt
  src/com/reco1l/osu/hud/HUDElement.kt
  src/com/reco1l/osu/hud/IGameplayEvents.kt
  src/com/reco1l/osu/hud/editor/HUDElementSelector.kt
  src/com/reco1l/osu/hud/elements/HUDTapsPerSecondCounter.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameObjectListener.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplayModernSpinner.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplaySpinner.java
Labels: size/M

#502 Add Traceable mod
  assets/gfx/selection-mod-traceable.png
  src/com/reco1l/osu/multiplayer/MultiplayerConversion.kt
  src/com/rian/osu/difficulty/calculator/StandardPerformanceCalculator.kt
  src/com/rian/osu/mods/ModTraceable.kt
  src/com/rian/osu/utils/ModUtils.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameHelper.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplayHitCircle.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplayModernSpinner.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplaySlider.java
  src/ru/nsu/ccfit/zuev/osu/game/GameplaySpinner.java
  src/ru/nsu/ccfit/zuev/osu/game/mods/GameMod.java
  src/ru/nsu/ccfit/zuev/osu/menu/ModMenu.java
  src/ru/nsu/ccfit/zuev/osu/scoring/StatisticV2.java
Labels: size/L

#503 Add osu!droid difficulty calculation for Traceable mod
  src/com/rian/osu/difficulty/DifficultyHitObject.kt
  src/com/rian/osu/difficulty/DroidDifficultyHitObject.kt
  src/com/rian/osu/difficulty/calculator/DroidDifficultyCalculator.kt
  src/com/rian/osu/difficulty/evaluators/DroidFlashlightEvaluator.kt
  src/com/rian/osu/difficulty/evaluators/DroidVisualEvaluator.kt
  src/com/rian/osu/difficulty/evaluators/StandardFlashlightEvaluator.kt
  src/com/rian/osu/difficulty/skills/DroidFlashlight.kt
  src/com/rian/osu/difficulty/skills/DroidVisual.kt
  src/com/rian/osu/difficulty/skills/StandardFlashlight.kt
Labels: size/L

#505 Abstractify `HUDStatisticCounter`
  src/com/reco1l/osu/hud/elements/HUDNotesPerSecondCounter.kt
  src/com/reco1l/osu/hud/elements/HUDStatisticsCounters.kt
  src/com/reco1l/osu/hud/elements/HUDTapsPerSecondCounter.kt
Labels: size/M

#506 Small HUD refactor
  src/com/reco1l/osu/hud/GameplayHUD.kt
  src/com/reco1l/osu/hud/HUDElement.kt
  src/com/reco1l/osu/hud/IGameplayEvents.kt
  src/com/reco1l/osu/hud/editor/HUDElementSelector.kt
  src/com/reco1l/osu/hud/elements/HUDAccuracyCounter.kt
  src/com/reco1l/osu/hud/elements/HUDAverageOffsetCounter.kt
  src/com/reco1l/osu/hud/elements/HUDComboCounter.kt
  src/com/reco1l/osu/hud/elements/HUDHealthBar.kt
  src/com/reco1l/osu/hud/elements/HUDLinearSongProgress.kt
  src/com/reco1l/osu/hud/elements/HUDNotesPerSecondCounter.kt
  src/com/reco1l/osu/hud/elements/HUDPPCounter.kt
  src/com/reco1l/osu/hud/elements/HUDPieSongProgress.kt
  src/com/reco1l/osu/hud/elements/HUDScoreCounter.kt
  src/com/reco1l/osu/hud/elements/HUDSongProgress.kt
  src/com/reco1l/osu/hud/elements/HUDStatisticsCounters.kt
  src/com/reco1l/osu/hud/elements/HUDTapsPerSecondCounter.kt
  src/com/reco1l/osu/hud/elements/HUDUnstableRateCounter.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/L

#508 Add BPM counter
  src/com/reco1l/osu/hud/HUDElement.kt
  src/com/reco1l/osu/hud/elements/HUDBPMCounter.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/S

#509 Move beatmap leaderboard scoring mode to scoring switcher button
  assets/ranking_enabled.png
  assets/ranking_enabled_pp.png
  assets/ranking_enabled_score.png
  res/xml/settings_general.xml
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/ResourceManager.java
  src/ru/nsu/ccfit/zuev/osu/menu/ScoreBoard.java
  src/ru/nsu/ccfit/zuev/osu/menu/SongMenu.java
Labels: size/M

#511 Fix `HUDElement`s not detaching editor overlay and anchor line when being detached
  src/com/reco1l/osu/hud/HUDElement.kt
Labels: size/XS

#489 Make gameplay time completely based on audio time
  res/xml/settings_input.xml
  src/ru/nsu/ccfit/zuev/osu/Config.java
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/L

#510 Move temporary locals
  build.gradle
  res/values/strings_temporary_for_locals.xml
  res/xml/settings_input.xml
  src/com/reco1l/osu/hud/GameplayHUD.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/M

#513 Add support for dynamic speed multiplier adjustment in gameplay via `ModTimeRamp`
  src/com/rian/osu/mods/ModTimeRamp.kt
  src/com/rian/osu/utils/ModUtils.kt
  src/ru/nsu/ccfit/zuev/osu/game/GameScene.java
Labels: size/M
